export const STORAGE_KEY='dotabyss:unified:v1';
export const ABYSS_COUNT=6;
export const G_COUNT=2;
export const STAM_INTERVAL=3*60*1000;
export const IDLE_CAP_MS=12*60*60*1000;
export const IDLE_LEAD_MS=5*60*1000;
export const G_INTERVAL=5*60*1000;
export const SL_STAM_INTERVAL=12*60*1000;
export const SL_ORB_INTERVAL=6*60*60*1000;
export const SL_STAM_MAX=80;
export const SL_ORB_MAX=4;
export const RANK_MIN=1;
export const RANK_MAX=200;
export const STAM_MAX_BASE=240;
export const STAM_MAX_PER_LEVEL=5;
export const dayKey=(hour=5,date=new Date())=>{const d=new Date(date);if(d.getHours()<hour)d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const weekKey=(date=new Date())=>{const d=new Date(date);if(d.getHours()<5)d.setDate(d.getDate()-1);d.setDate(d.getDate()-((d.getDay()+6)%7));return dayKey(0,d)};
export const maxForRank=rank=>Math.min(999,STAM_MAX_BASE+(Math.max(RANK_MIN,Math.min(RANK_MAX,Math.floor(Number(rank)||1)))-1)*STAM_MAX_PER_LEVEL);
export const defaultAbyss=()=>({label:'',rank:1,stamCurrent:0,stamMax:240,stamStart:null,stamRunning:false,idleStart:null,idleCapMs:IDLE_CAP_MS,idleRunning:false,missionDone:false,weeklyDone:false});
export const defaultG=()=>({label:'',stamCurrent:0,stamMax:130,stamStart:null,stamRunning:false,missionDone:false});
export const defaultTimer=()=>({current:0,start:null,running:false});
export const defaultState=()=>({slots:Array.from({length:ABYSS_COUNT},defaultAbyss),dailyDate:'',weeklyDate:'',g:{slots:Array.from({length:G_COUNT},defaultG),dailyDate:''},sl:{stamina:defaultTimer(),orb:defaultTimer()}});
