import {ABYSS_COUNT,G_COUNT,STORAGE_KEY,defaultAbyss,defaultG,defaultState,defaultTimer,dayKey,weekKey,maxForRank} from './constants.js';
const num=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const bool=value=>Boolean(value);
function normalizeAbyss(raw={}){const rank=Math.max(1,Math.min(200,Math.floor(num(raw.rank,1))));const max=Math.max(1,Math.min(999,num(raw.stamMax,maxForRank(rank))));return {...defaultAbyss(),...raw,rank,stamCurrent:Math.max(0,Math.min(max,num(raw.stamCurrent,0))),stamMax:max,stamStart:raw.stamStart||null,stamRunning:bool(raw.stamRunning),idleStart:raw.idleStart||null,idleCapMs:Math.max(0,num(raw.idleCapMs,12*60*60*1000)),idleRunning:bool(raw.idleRunning),missionDone:bool(raw.missionDone),weeklyDone:bool(raw.weeklyDone)};}
function normalizeG(raw={}){const max=Math.max(1,Math.min(999,num(raw.stamMax,130)));return {...defaultG(),...raw,stamCurrent:Math.max(0,Math.min(max,num(raw.stamCurrent,0))),stamMax:max,stamStart:raw.stamStart||null,stamRunning:bool(raw.stamRunning),missionDone:bool(raw.missionDone)};}
function normalizeTimer(raw={}){return {...defaultTimer(),...raw,current:Math.max(0,num(raw.current,0)),start:raw.start||null,running:bool(raw.running)};}
export function load(){let raw={};try{raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{}const state=defaultState();state.slots=Array.from({length:ABYSS_COUNT},(_,i)=>normalizeAbyss(raw.slots?.[i]));state.dailyDate=raw.dailyDate||dayKey();state.weeklyDate=raw.weeklyDate||weekKey();state.g.slots=Array.from({length:G_COUNT},(_,i)=>normalizeG(raw.g?.slots?.[i]));state.g.dailyDate=raw.g?.dailyDate||dayKey(1);state.sl.stamina=normalizeTimer(raw.sl?.stamina);state.sl.orb=normalizeTimer(raw.sl?.orb);return state;}
export function save(state){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true}catch{return false}}
export function resetDates(state,now=new Date()){let changed=false;const daily=dayKey(5,now);if(state.dailyDate!==daily){state.dailyDate=daily;state.slots.forEach(slot=>slot.missionDone=false);changed=true}const weekly=weekKey(now);if(state.weeklyDate!==weekly){state.weeklyDate=weekly;state.slots.forEach(slot=>slot.weeklyDone=false);changed=true}const gd=dayKey(1,now);if(state.g.dailyDate!==gd){state.g.dailyDate=gd;state.g.slots.forEach(slot=>slot.missionDone=false);changed=true}return changed;}
